version: 2.1
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: golang:1.15.12-stretch
    steps:
      - checkout
      - run:
          name: lint-dockerfile
          command: |
            curl -ssl -o /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
            chmod +x /bin/hadolint
            hadolint Dockerfile
  deploy:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build-app-karsajobs
          command: |
            docker build -t ghcr.io/vans-id/karsajobs-ui:latest .
            docker login ghcr.io -u vans-id -p $GITHUB_TOKEN
            docker push ghcr.io/vans-id/karsajobs-ui:latest
workflows:
  version: 2
  build:
    jobs:
      - test
      - deploy:
          requires:
            - test